image: ghcr.io/shesek/bitpod:gui
# To use the local Dockerfile:
#   file: .gitpod.Dockerfile

checkoutLocation: bitpod
workspaceLocation: bitpod/bitcoin.code-workspace

tasks:
  - name: bitcoin core
    init: |
      { . gitpod-init.sh; } 2>&1 | tee -a /workspace/init.log
      gp sync-done init
    command: |
      [ -n "$WITH_GUI" ] && gp-vncsession
      cd /workspace/bitcoin
      echo 🟢 Starting bitcoin...
      bitcoin-qt $BITCOIN_OPT

  - name: node rpc
    openMode: split-right
    init: echo Waiting for bitcoind to build... && gp sync-await init
    command: |
      cd /workspace/bitcoin
      echo Waiting for bitcoind to start...
      gp ports await 18443 &&
      bitcoin-cli -rpcwait getnetworkinfo | jq -r .subversion &&
      . /workspace/bitpod/bitcoin-setup.sh &&
      gp sync-done bitcoin-setup

  - name: tests
    before: |
      [[ -v TEST || -v CHECK ]] || exit 0
    init: echo Waiting for bitcoind to build... && gp sync-await init
    command: |
      if [[ -v CHECK ]]; then bitcoin-check $CHECK; fi &&
      if [[ -v TEST ]]; then bitcoin-test $(cd /workspace/bitcoin/test/functional && echo $TEST); fi

  - name: btc-rpc-explorer
    env:
      BTCEXP_HOST: 0.0.0.0
      BTCEXP_BASIC_AUTH_PASSWORD: 1234
      BTCEXP_BITCOIND_URI: http://host.docker.internal:18443
      BTCEXP_BITCOIND_COOKIE: /etc/bitcoin.cookie
    #init: |
    #  cd btc-rpc-explorer &&
    #  rm .git &&
    #  docker build -t btc-rpc-explorer .
    command: |
      echo Waiting for bitcoind to start... &&
      gp sync-await bitcoin-setup &&
      echo Running btc-rpc-explorer on $(gp url 3002) &&
      (docker start explorer 2> /dev/null \
      || docker run -d --name explorer --restart on-failure \
          -p 3002:3002 --add-host host.docker.internal:host-gateway \
          -e BTCEXP_HOST -e BTCEXP_BITCOIND_URI -e BTCEXP_BITCOIND_COOKIE \
          -v ~/.bitcoin/regtest/.cookie:/etc/bitcoin.cookie \
          ghcr.io/shesek/btc-rpc-explorer) &&
      exit 0 # close the terminal window

ports:
  - port: 18443
    name: bitcoin rpc
    description: Bitcoin Core JSONRPC server
    onOpen: ignore

  - port: 3002
    name: block explorer
    description: A btc-rpc-explorer instance connected to the local regtest bitcoind.
    onOpen: notify # changed to 'notify' in gui mode

  - port: 6080
    name: bitcoin-qt
    description: VNC client for accessing the bitcoin-qt GUI
    onOpen: open-preview

  # internal port for VNC, not accessed directly
  - port: 5900
    onOpen: ignore

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: false
    pullRequestsFromForks: false

vscode:
  extensions:
    - eamodio.gitlens
    - editorconfig.editorconfig
    - llvm-vs-code-extensions.vscode-clangd
